version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: api
    command: uvicorn watchdog.server_app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: worker
    command: celery -A watchdog.celery_app worker --loglevel=info
    volumes:
      - ./src:/app/src
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
