[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "watchdog"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = "src"

[tool.pylint]
init-hook = 'import sys; sys.path.append("src")'
disable = "C0114"